Squashed commit of the following:
commit ddffa6c5fd3d256e02f26f043e83e99b4093e8bb
Author: Code Manager <code_manager@agent-694ff4-0>
Date:   Tue Oct 10 13:11:34 2023 +0000

    Fix undefined local 'path'

    Fixed failing tests after refactoring around(:all) into before/after(:all):  ``Failure/Error: FileUtils.rm_f(path)
    NameError:
      undefined local variable or method `path'...``

commit 10821c54a280dd3a3cfb4a3556bcef409b40d9f2
Author: Gavin Didrichsen <gavin.didrichsen@gmail.com>
Date:   Thu Oct 5 21:00:17 2023 +0100

    (CAT-1488) - Fix some rubocop warnings

    Signed-off-by: Gavin Didrichsen <gavin.didrichsen@gmail.com>

commit 831c41da83631ef334d3736b18ff606a327b52f6
Author: Gavin Didrichsen <gavin.didrichsen@gmail.com>
Date:   Thu Oct 5 20:34:03 2023 +0100

    (CAT-1488) - Split around(:all) into before/after(:all)

    This fixes duplicate code warnings occurring during the acceptance
    tests.

    Signed-off-by: Gavin Didrichsen <gavin.didrichsen@gmail.com>

commit d2cec4bada6775d221ad26a00743de521ec29721
Author: Gavin Didrichsen <gavin.didrichsen@gmail.com>
Date:   Thu Oct 5 20:32:51 2023 +0100

    (CAT-1488) - Refactor duplicated shared examples and context

    This fixes duplicate definition warnings in the acceptance tests.

    Signed-off-by: Gavin Didrichsen <gavin.didrichsen@gmail.com>